### ISSUE TITLE
The page freeze

### ISSUE THREAD

**Issue by SamuelRott** [jfalxa/plan#1]
![screenshot from 2017-10-27 12-58-13](https://user-images.githubusercontent.com/12135011/32101055-db3de3d4-bb16-11e7-8032-81eb4d14cadd.png)
The page freeze and after a while the browser ask you  if you want  to kill it.

How to reproduce:

1) Draw a complete box
2) start a new line FROM a point that is not part of the box TO a point of the box

**Comment by jfalxa** [comment]
Closed by https://github.com/jfalxa/plan/commit/f536bc9bd747810298b255d3b3b0850104ff07e6
